package starbudsPackage;
// Generated 25 avr. 2017 16:54:05 by Hibernate Tools 4.3.1

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.servlet.http.HttpServletRequest;

/**
 * Commande generated by hbm2java
 */
public class Commande implements java.io.Serializable {

    private Integer id;
    private Serveur serveur;
    private int numero;
    private Date date;
    private String etat;
    private Set<Facture> factures = new HashSet<Facture>(0);

    public Commande() {
    }

    public Commande(Serveur serveur, int numero, Date date, String etat) {
        this.serveur = serveur;
        this.numero = numero;
        this.date = date;
        this.etat = etat;
    }

    public Commande(Serveur serveur, int numero, Date date, String etat, Set<Facture> factures) {
        this.serveur = serveur;
        this.numero = numero;
        this.date = date;
        this.etat = etat;
        this.factures = factures;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Serveur getServeur() {
        return this.serveur;
    }

    public void setServeur(Serveur serveur) {
        this.serveur = serveur;
    }

    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getEtat() {
        return this.etat;
    }

    public void setEtat(String etat) {
        this.etat = etat;
    }

    public Set<Facture> getFactures() {
        return this.factures;
    }

    public void setFactures(Set<Facture> factures) {
        this.factures = factures;
    }
/*
    public static Commande getCommande() {

        ArrayList<String> CommandeList = new ArrayList<String>();

        try {

            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/starbuds?" + "user=root&password=root");
            PreparedStatement pst = conn.prepareStatement("Select * from commande");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {

                CommandeList.add(rs.getString(1));
                CommandeList.add(rs.getString(2));
                CommandeList.add(rs.getString(3));
                CommandeList.add(rs.getString(4));
                CommandeList.add(rs.getString(5));

                Commande cmd = (Commande) setAttribute("commande", CommandeList);

            for (String object : CommandeList) {
                out.println(object);
            }
            }
        } catch (Exception e) {
            out.println("Something went wrong !! Please try again");
        }

    }*/

}
