package starbudsPackage;
// Generated 25 avr. 2017 16:54:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Commande generated by hbm2java
 */
public class Commande  implements java.io.Serializable {


     private Integer id;
     private Serveur serveur;
     private int numero;
     private Date date;
     private String etat;
     private Set<Facture> factures = new HashSet<Facture>(0);

    public Commande() {
    }

	
    public Commande(Serveur serveur, int numero, Date date, String etat) {
        this.serveur = serveur;
        this.numero = numero;
        this.date = date;
        this.etat = etat;
    }
    public Commande(Serveur serveur, int numero, Date date, String etat, Set<Facture> factures) {
       this.serveur = serveur;
       this.numero = numero;
       this.date = date;
       this.etat = etat;
       this.factures = factures;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Serveur getServeur() {
        return this.serveur;
    }
    
    public void setServeur(Serveur serveur) {
        this.serveur = serveur;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }
    public Set<Facture> getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set<Facture> factures) {
        this.factures = factures;
    }




}


