package starbudsPackage;
// Generated 25 avr. 2017 16:54:05 by Hibernate Tools 4.3.1



/**
 * Facture generated by hbm2java
 */
public class Facture  implements java.io.Serializable {


     private Integer id;
     private Commande commande;
     private float montant;
     private String etat;

    public Facture() {
    }

    public Facture(Commande commande, float montant, String etat) {
       this.commande = commande;
       this.montant = montant;
       this.etat = etat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }
    public float getMontant() {
        return this.montant;
    }
    
    public void setMontant(float montant) {
        this.montant = montant;
    }
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }




}


