package starbudsPackage;
// Generated 25 avr. 2017 16:54:05 by Hibernate Tools 4.3.1



/**
 * Musique generated by hbm2java
 */
public class Musique  implements java.io.Serializable {


     private Integer id;
     private boolean isActive;

    public Musique() {
    }

    public Musique(boolean isActive) {
       this.isActive = isActive;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


