package starbudsPackage;
// Generated 25 avr. 2017 16:54:05 by Hibernate Tools 4.3.1

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.servlet.http.HttpServletRequest;
import starbudsPackage.Serveur;

/**
 * Serveur generated by hbm2java
 */
public class Serveur implements java.io.Serializable {

    private Integer id;
    private String nom;
    private String prenom;
    private String login;
    private String mdp;
    private boolean enActivite;
    private Set<Commande> commandes = new HashSet<Commande>(0);

    public Serveur() {
    }

    public Serveur(Integer Id, String Nom, String Prenom, boolean Activite) {
        id = Id;
        nom = Nom;
        prenom = Prenom;
        enActivite = Activite;
    }

    public Serveur(String nom, String prenom, String login, String mdp, boolean enActivite) {
        this.nom = nom;
        this.prenom = prenom;
        this.login = login;
        this.mdp = mdp;
        this.enActivite = enActivite;
    }

    public Serveur(String nom, String prenom, String login, String mdp, boolean enActivite, Set<Commande> commandes) {
        this.nom = nom;
        this.prenom = prenom;
        this.login = login;
        this.mdp = mdp;
        this.enActivite = enActivite;
        this.commandes = commandes;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getMdp() {
        return this.mdp;
    }

    public void setMdp(String mdp) {
        this.mdp = mdp;
    }

    public boolean isEnActivite() {
        return this.enActivite;
    }

    public void setEnActivite(boolean enActivite) {
        this.enActivite = enActivite;
    }

    public Set<Commande> getCommandes() {
        return this.commandes;
    }

    public void setCommandes(Set<Commande> commandes) {
        this.commandes = commandes;
    }

    public ArrayList getServeur() {

        ArrayList<Serveur> serveurList = new ArrayList<Serveur>();

        try {

            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/starbuds?" + "user=root&password=root");
            PreparedStatement pst = conn.prepareStatement("Select * from serveur");
            ResultSet rs = pst.executeQuery();

            Serveur serveur = null;

            while (rs.next()) {

                //commande = new Commande();
                //serveur = (Serveur) getServeur((rs.getInt(5)));
                serveur = new Serveur();

                serveur.setId((rs.getInt(1)));
                serveur.setNom((rs.getString(2)));
                serveur.setPrenom((rs.getString(3)));
                serveur.setEnActivite((rs.getBoolean(6)));

                serveurList.add(serveur);

            }
        } catch (Exception e) {
            System.out.println("Commande non trouvé");
        }
        return serveurList;
    }

}
